version: '3.8'

services:
    web:
        image: encuestas-web-image
        container_name: encuestas-web
        build:
            context: .
            dockerfile: ./web/Dockerfile
        ports:
            - "80:80"

    server:
        build: 
            context: .
            dockerfile: ./server/Dockerfile
        image: node-mysql-server
        container_name: encuestas-api
        depends_on: 
            - mysql
        stdin_open: true
        tty: true
        ports:
            - "3000:3000"

    mysql:
        image: mysql
        # restart: always
        env_file: ./server/.env
        environment:
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        ports:
            - "3306:3306"
        volumes:
            - db-config:/etc/mysql
            - db-data:/var/lib/mysql
            - ./db/backup/files/:/data_backup/data

volumes: 
    db-config:
    db-data: